CREATE TABLE [dbo].[Employees]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL, 
    [Email] NVARCHAR(128) NOT NULL, 
    [Name] NVARCHAR(128) NOT NULL, 
    [Lastname] NVARCHAR(128) NOT NULL, 
    CONSTRAINT [PK_Employees] PRIMARY KEY ([Id])
)
